### ISSUE TITLE
@types/express should be a dependency

### ISSUE THREAD

**Issue by brokenmass** [express-promise-router/express-promise-router#66]
as yarn v2 has become more strict with module resolutions, `express-promise-router` should to explicitly define `@types/express` in its dependencies (not `devDependencies`) for the `express` imported in the index.d.ts to be resolved correctly.

as a temporary workaround yarnv2 / typescript users can add the following to their yarnrc.yml

```yml
packageExtensions:
  express-promise-router@*:
    dependencies:
      '@types/express': '^4.11.0'
```
